// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLf9av8Gz6l8yjSdC_dYYRRqBYZo-pyJo',
    appId: '1:359367635485:web:adcbf62203d77f2ef7ccf4',
    messagingSenderId: '359367635485',
    projectId: 'fir-auth-68d65',
    authDomain: 'fir-auth-68d65.firebaseapp.com',
    storageBucket: 'fir-auth-68d65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrFcB9r-v6Jio4I60bjmRxu1StDUOvsXM',
    appId: '1:359367635485:android:8fdc85e3166a1124f7ccf4',
    messagingSenderId: '359367635485',
    projectId: 'fir-auth-68d65',
    storageBucket: 'fir-auth-68d65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkgd7ZCQuF0KOhj0vieU3V54OTB8ssE2o',
    appId: '1:359367635485:ios:f9862ed7773a1a55f7ccf4',
    messagingSenderId: '359367635485',
    projectId: 'fir-auth-68d65',
    storageBucket: 'fir-auth-68d65.firebasestorage.app',
    iosBundleId: 'com.example.firebaseUserauthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkgd7ZCQuF0KOhj0vieU3V54OTB8ssE2o',
    appId: '1:359367635485:ios:f9862ed7773a1a55f7ccf4',
    messagingSenderId: '359367635485',
    projectId: 'fir-auth-68d65',
    storageBucket: 'fir-auth-68d65.firebasestorage.app',
    iosBundleId: 'com.example.firebaseUserauthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLf9av8Gz6l8yjSdC_dYYRRqBYZo-pyJo',
    appId: '1:359367635485:web:5535dcc9118338adf7ccf4',
    messagingSenderId: '359367635485',
    projectId: 'fir-auth-68d65',
    authDomain: 'fir-auth-68d65.firebaseapp.com',
    storageBucket: 'fir-auth-68d65.firebasestorage.app',
  );
}
